package com.odenzo.etrade.models.responses

import com.odenzo.etrade.models.*
import com.odenzo.etrade.models.utils.CirceUtils
import io.circe.*
import io.circe.generic.semiauto.{deriveCodec, deriveEncoder}
import io.circe.syntax.*

case class PreviewOrderRs(previewOrderResponse: PreviewOrderResponse)

object PreviewOrderRs:
  given Codec[PreviewOrderRs] = CirceUtils.capitalizeCodec(deriveCodec)

case class PreviewOrderResponse(
    orderType: OrderType,                              //	string	The type of order being placed	EQ, OPTN, SPREADS, BUY_WRITES, BUTTERFLY,
    // IRON_BUTTERFLY, CONDOR, IRON_CONDOR, MF, MMF
    messageList: Messages,                             //	The object for the message list
    totalOrderValue: Amount,                           //	number	The total order value
    totalCommission: Amount,                           //	number	The total commission
    order: List[Detail],                               //	The details of the order
    previewIds: List[PreviewId],                       //	This parameter is required and must specify the numeric preview ID from the preview and the other
    // parameters of this request must match the parameters of the preview.
    previewTime: ETimestamp,                           // 	integer (int64)	The preview time
    dstFlag: Option[Boolean],                          //	boolean	Indicator flag identifying whether daylight savings time is applicable or not
    accountId: String,                                 // 	string	The numeric account ID
    optionLevelCd: Option[Int],                        //	integer (int32)	The code that designates the applicable options level
    marginLevelCd: MarginLevel,                        // 	string	The code that designates the applicable margin level
    portfolioMargin: PortfolioMargin,                  // 	The portfolio margin details for the user
    isEmployee: Option[Boolean],                       //	boolean	Indicator flag identifying whether user is an E*TRADE employee
    commissionMessage: String,                         // 	string	The commission message
    disclosure: Disclosure,                            // 	The disclosure designation
    clientOrderId: String,                             // A reference ID generated by the developer
    marginBpDetails: Option[MarginBuyingPowerDetails], //	Margin Buying Power Details for the user
    cashBpDetails: CashBuyingPowerDetails,             //	Cash Buying Power Details for the user
    dtBpDetails: Option[DtBuyingPowerDetails]          //	Day Trading Buying Power Details for the user
)
