object Version {

  val blindSightLog      = "1.4.0"
  val catsEffect         = "3.3.5"
  val catsMice           = "1.0.10"
  val catsRetry          = "3.1.0"
  val cats               = "2.7.0"
  val catsCollections    = "0.9.3"
  val circeGenericExtras = "0.15.0-M1"
  val circeOptics        = "0.15.0-M1"
  val circe              = "0.15.0-M1"
  val doobie             = "1.0.0-RC2"
  val fs2                = "3.2.5"
  val http4s             = "1.0.0-M31"
  val logback            = "1.2.10"
  val monocle            = "3.1.0"
  val munitCats          = "1.0.7"
  val munit              = "1.0.0-M1"
  val oslib              = "0.8.1"
  val pprint             = "0.7.1"
  val scalaXML           = "2.0.1"
  val scodecBits         = "1.18"
  val scodecCats         = "1.0.0"
  val scodec             = "1.11.7"
  val scribe             = "3.7.1"
  val squants            = "1.7.0"
  val sttpClient         = "3.4.1"
  val tapir              = "0.19.3"
}
